// Code generated by "stringer -type NodePhase"; DO NOT EDIT.

package federation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodePhaseBooting-0]
	_ = x[NodePhaseJoining-1]
	_ = x[NodePhaseInserting-2]
	_ = x[NodePhaseRouting-3]
	_ = x[NodePhaseShutdown-4]
}

const _NodePhase_name = "NodePhaseBootingNodePhaseJoiningNodePhaseInsertingNodePhaseRoutingNodePhaseShutdown"

var _NodePhase_index = [...]uint8{0, 16, 32, 50, 66, 83}

func (i NodePhase) String() string {
	if i < 0 || i >= NodePhase(len(_NodePhase_index)-1) {
		return "NodePhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodePhase_name[_NodePhase_index[i]:_NodePhase_index[i+1]]
}
