// Code generated by "stringer -type MessageActorType"; DO NOT EDIT.

package transport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageActorTypeEmpty-0]
	_ = x[MessageActorTypeTransport-1]
	_ = x[MessageActorTypeFederation-2]
	_ = x[MessageActorTypeRouting-3]
	_ = x[MessageActorTypeCM-4]
	_ = x[MessageActorTypeNamingGateway-5]
	_ = x[MessageActorTypeNamingStoreService-6]
	_ = x[MessageActorTypeApplicationHostManager-7]
	_ = x[MessageActorTypeApplicationHost-8]
	_ = x[MessageActorTypeFabricRuntimeManager-9]
	_ = x[MessageActorTypeFMM-10]
	_ = x[MessageActorTypeFM-11]
	_ = x[MessageActorTypeRA-12]
	_ = x[MessageActorTypeRS-13]
	_ = x[MessageActorTypeServiceResolver-14]
	_ = x[MessageActorTypeHosting-15]
	_ = x[MessageActorTypeHM-16]
	_ = x[MessageActorTypeServiceRoutingAgent-17]
	_ = x[MessageActorTypeIS-18]
	_ = x[MessageActorTypeFabricActivator-19]
	_ = x[MessageActorTypeFabricActivatorClient-20]
	_ = x[MessageActorTypeIpc-21]
	_ = x[MessageActorTypeFileStoreService-22]
	_ = x[MessageActorTypeTvs-23]
	_ = x[MessageActorTypeRM-24]
	_ = x[MessageActorTypeFileSender-25]
	_ = x[MessageActorTypeFileReceiver-26]
	_ = x[MessageActorTypeFileTransferClient-27]
	_ = x[MessageActorTypeFileTransferGateway-28]
	_ = x[MessageActorTypeTransportSendTarget-29]
	_ = x[MessageActorTypeEntreeServiceProxy-30]
	_ = x[MessageActorTypeEntreeServiceTransport-31]
	_ = x[MessageActorTypeHostedServiceActivator-32]
	_ = x[MessageActorTypeNM-33]
	_ = x[MessageActorTypeDirectMessagingAgent-34]
	_ = x[MessageActorTypeSecurityContext-35]
	_ = x[MessageActorTypeServiceCommunicationActor-36]
	_ = x[MessageActorTypeRestartManager-37]
	_ = x[MessageActorTypeRestartManagerClient-38]
	_ = x[MessageActorTypeFAS-39]
	_ = x[MessageActorTypeTestabilitySubsystem-40]
	_ = x[MessageActorTypeUOS-41]
	_ = x[MessageActorTypeBA-42]
	_ = x[MessageActorTypeBRS-43]
	_ = x[MessageActorTypeBAP-44]
	_ = x[MessageActorTypeContainerActivatorService-45]
	_ = x[MessageActorTypeContainerActivatorServiceClient-46]
	_ = x[MessageActorTypeResourceMonitor-47]
	_ = x[MessageActorTypeCSS-48]
	_ = x[MessageActorTypeNetworkInventoryService-49]
	_ = x[MessageActorTypeNetworkInventoryAgent-50]
	_ = x[MessageActorTypeGatewayResourceManager-51]
	_ = x[MessageActorTypeFederationAgent-54]
	_ = x[MessageActorTypeFederationProxy-55]
	_ = x[MessageActorTypeSystemServiceTcpConnection-56]
	_ = x[MessageActorTypeNamingGatewayService-57]
	_ = x[MessageActorTypeSystemServiceConfigSetting-58]
	_ = x[MessageActorTypeSystemCache-59]
	_ = x[MessageActorTypeEndValidEnum-60]
	_ = x[MessageActorTypeFirstValidEnum-0]
	_ = x[MessageActorTypeLastValidEnum-59]
	_ = x[MessageActorTypeWindowsFabricTestApi-65535]
	_ = x[MessageActorTypeGenericTestActor-65536]
	_ = x[MessageActorTypeGenericTestActor2-65537]
	_ = x[MessageActorTypeDistributedSession-65538]
	_ = x[MessageActorTypeIpcTestActor1-65539]
	_ = x[MessageActorTypeIpcTestActor2-65540]
}

const (
	_MessageActorType_name_0 = "MessageActorTypeEmptyMessageActorTypeTransportMessageActorTypeFederationMessageActorTypeRoutingMessageActorTypeCMMessageActorTypeNamingGatewayMessageActorTypeNamingStoreServiceMessageActorTypeApplicationHostManagerMessageActorTypeApplicationHostMessageActorTypeFabricRuntimeManagerMessageActorTypeFMMMessageActorTypeFMMessageActorTypeRAMessageActorTypeRSMessageActorTypeServiceResolverMessageActorTypeHostingMessageActorTypeHMMessageActorTypeServiceRoutingAgentMessageActorTypeISMessageActorTypeFabricActivatorMessageActorTypeFabricActivatorClientMessageActorTypeIpcMessageActorTypeFileStoreServiceMessageActorTypeTvsMessageActorTypeRMMessageActorTypeFileSenderMessageActorTypeFileReceiverMessageActorTypeFileTransferClientMessageActorTypeFileTransferGatewayMessageActorTypeTransportSendTargetMessageActorTypeEntreeServiceProxyMessageActorTypeEntreeServiceTransportMessageActorTypeHostedServiceActivatorMessageActorTypeNMMessageActorTypeDirectMessagingAgentMessageActorTypeSecurityContextMessageActorTypeServiceCommunicationActorMessageActorTypeRestartManagerMessageActorTypeRestartManagerClientMessageActorTypeFASMessageActorTypeTestabilitySubsystemMessageActorTypeUOSMessageActorTypeBAMessageActorTypeBRSMessageActorTypeBAPMessageActorTypeContainerActivatorServiceMessageActorTypeContainerActivatorServiceClientMessageActorTypeResourceMonitorMessageActorTypeCSSMessageActorTypeNetworkInventoryServiceMessageActorTypeNetworkInventoryAgentMessageActorTypeGatewayResourceManager"
	_MessageActorType_name_1 = "MessageActorTypeFederationAgentMessageActorTypeFederationProxyMessageActorTypeSystemServiceTcpConnectionMessageActorTypeNamingGatewayServiceMessageActorTypeSystemServiceConfigSettingMessageActorTypeSystemCacheMessageActorTypeEndValidEnum"
	_MessageActorType_name_2 = "MessageActorTypeWindowsFabricTestApiMessageActorTypeGenericTestActorMessageActorTypeGenericTestActor2MessageActorTypeDistributedSessionMessageActorTypeIpcTestActor1MessageActorTypeIpcTestActor2"
)

var (
	_MessageActorType_index_0 = [...]uint16{0, 21, 46, 72, 95, 113, 142, 176, 214, 245, 281, 300, 318, 336, 354, 385, 408, 426, 461, 479, 510, 547, 566, 598, 617, 635, 661, 689, 723, 758, 793, 827, 865, 903, 921, 957, 988, 1029, 1059, 1095, 1114, 1150, 1169, 1187, 1206, 1225, 1266, 1313, 1344, 1363, 1402, 1439, 1477}
	_MessageActorType_index_1 = [...]uint8{0, 31, 62, 104, 140, 182, 209, 237}
	_MessageActorType_index_2 = [...]uint8{0, 36, 68, 101, 135, 164, 193}
)

func (i MessageActorType) String() string {
	switch {
	case 0 <= i && i <= 51:
		return _MessageActorType_name_0[_MessageActorType_index_0[i]:_MessageActorType_index_0[i+1]]
	case 54 <= i && i <= 60:
		i -= 54
		return _MessageActorType_name_1[_MessageActorType_index_1[i]:_MessageActorType_index_1[i+1]]
	case 65535 <= i && i <= 65540:
		i -= 65535
		return _MessageActorType_name_2[_MessageActorType_index_2[i]:_MessageActorType_index_2[i+1]]
	default:
		return "MessageActorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
